npm run generate-test-1 -- --haxe --output ../colyseus-hx/tests/schema/primitivetypes --namespace schema.primitivetypes
npm run generate-test-2 -- --haxe --output ../colyseus-hx/tests/schema/childschematypes --namespace schema.childschematypes
npm run generate-test-3 -- --haxe --output ../colyseus-hx/tests/schema/arrayschematypes --namespace schema.arrayschematypes
npm run generate-test-4 -- --haxe --output ../colyseus-hx/tests/schema/mapschematypes --namespace schema.mapschematypes
npm run generate-test-5 -- --haxe --output ../colyseus-hx/tests/schema/inheritedtypes --namespace schema.inheritedtypes
npm run generate-test-6 -- --haxe --output ../colyseus-hx/tests/schema/mapschemaint8 --namespace schema.mapschemaint8
npm run generate-test-7 -- --haxe --output ../colyseus-hx/tests/schema/backwardsforwards --namespace schema.backwardsforwards
npm run generate-test-8 -- --haxe --output ../colyseus-hx/tests/schema/filteredtypes --namespace schema.filteredtypes
npm run generate-test-9 -- --haxe --output ../colyseus-hx/tests/schema/instancesharingtypes --namespace schema.instancesharingtypes
npm run generate-test-10 -- --haxe --output ../colyseus-hx/tests/schema/callbacks --namespace schema.callbacks
