npm run generate-test-1 -- --lua --output ../colyseus-defold/test/schema/PrimitiveTypes --namespace test.schema.PrimitiveTypes
npm run generate-test-2 -- --lua --output ../colyseus-defold/test/schema/ChildSchemaTypes --namespace test.schema.ChildSchemaTypes
npm run generate-test-3 -- --lua --output ../colyseus-defold/test/schema/ArraySchemaTypes --namespace test.schema.ArraySchemaTypes
npm run generate-test-4 -- --lua --output ../colyseus-defold/test/schema/MapSchemaTypes --namespace test.schema.MapSchemaTypes
npm run generate-test-5 -- --lua --output ../colyseus-defold/test/schema/InheritedTypes --namespace test.schema.InheritedTypes
npm run generate-test-6 -- --lua --output ../colyseus-defold/test/schema/MapSchemaInt8 --namespace test.schema.MapSchemaInt8
npm run generate-test-7 -- --lua --output ../colyseus-defold/test/schema/BackwardsForwards --namespace test.schema.BackwardsForwards
npm run generate-test-8 -- --lua --output ../colyseus-defold/test/schema/FilteredTypes --namespace test.schema.FilteredTypes
npm run generate-test-9 -- --lua --output ../colyseus-defold/test/schema/InstanceSharingTypes --namespace test.schema.InstanceSharingTypes
npm run generate-test-10 -- --lua --output ../colyseus-defold/test/schema/Callbacks --namespace test.schema.Callbacks
