default:
	g++ -std=c++11 -o usage_primitive_types usage_primitive_types.cpp
	g++ -std=c++11 -o usage_child_schema_types usage_child_schema_types.cpp
	g++ -std=c++11 -o usage_array_schema_types usage_array_schema_types.cpp
	g++ -std=c++11 -o usage_map_schema_types usage_map_schema_types.cpp
	g++ -std=c++11 -o usage_inherited_types usage_inherited_types.cpp
